# Generated by Django 6.0.5 on 2026-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="darta",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="darta_documents/"),
        ),
    ]
