# Generated by Django 6.0.5 on 2026-06-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_darta_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="chalan",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="chalan_documents/"
            ),
        ),
    ]
