# Generated by Django 6.0.5 on 2026-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_chalan_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
